[package]
name = "cerberus-hydra-backend"
version = "0.1.0"
edition = "2021"
authors = ["Tony <tony@cerberuschain.com>", "Dave <dave@cerberuschain.com>"]
description = "Cerberus Chain: Hydra - Advanced Solana Memecoin Trading Bot Backend"

[dependencies]
actix-web = "4.5"
actix-web-actors = "4.3"
actix-cors = "0.7"
actix-files = "0.6"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Use only PostgreSQL features to avoid MySQL dependencies that require newer zeroize
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"], default-features = false }

redis = { version = "0.24", features = ["tokio-comp"] }
jsonwebtoken = "9.2"

# Use password-hash instead of bcrypt to avoid zeroize conflicts
password-hash = "0.4"
argon2 = "0.4"

uuid = { version = "1.0", features = ["v4", "serde"] }

# Use older Solana versions that are compatible with zeroize 1.3.0
solana-sdk = "1.14"
solana-client = "1.14"
solana-account-decoder = "1.14"

# Use compatible anchor version
anchor-client = "0.26"

reqwest = { version = "0.11", features = ["json", "stream"] }
tokio-tungstenite = "0.20"
aes-gcm = "0.10"
rand = "0.8"
hex = "0.4"
dotenv = "0.15"
config = "0.14"
log = "0.4"
env_logger = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"
lazy_static = "1.4"
governor = "0.6"
prometheus = "0.13"

[dev-dependencies]
actix-rt = "2.9"
actix-test = "0.1"